### ISSUE TITLE
es原生应该支持批量插入

### ISSUE THREAD

**Issue by steden** [farseer-go/elasticSearch#2]
```go
	for i := 0; i < lstPO.Count(); i++ {
		item := lstPO.Skip(i).Take(1).First()
		repository.taskLogES.Insert(item)
	}
```

1. 首先，即使要用循环，也不需要使用Skip(i).Take(1).First()这种方式。可以使用LstPO.Index(i)来获取。
2. 其次，repository.taskLogES.Insert应该要支持可变数量插入。这样可以直接使用repository.taskLogES.Insert(lstPO.ToArray()...)更优雅。
3. 另外，应该支持List插入就最好了。repository.taskLogES.InsertList(lstPO)
4. ES原生的是支持批量写入的，研究下。

2、3、4都要修改。
@gelin9527

**Comment by gelin9527** [comment]
已完成
