### ISSUE TITLE
未设置es_type字段时，需根据结构体的字体类型来做匹配

### ISSUE THREAD

**Issue by steden** [farseer-go/elasticSearch#5]
<img width="771" alt="image" src="https://user-images.githubusercontent.com/3379758/188879337-1cf6466f-2f80-42d1-98f4-e5831010b626.png">

如：
string类型，默认：[Keywords](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html)
bool类型，默认：[boolean](https://www.elastic.co/guide/en/elasticsearch/reference/current/boolean.html)
int、int16、int32，默认：[integer](https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html)
uint、uint16、uint32，默认：[integer](https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html)
int64、uint64，默认：[long](https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html)
float32、float64 默认：[double](https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html)
time.Time、dateTime.DateTime 默认：[date](https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html)
枚举类型，默认：[byte](https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html)
结构体，默认：[object](https://www.elastic.co/guide/en/elasticsearch/reference/current/object.html)
数组，默认：[object](https://www.elastic.co/guide/en/elasticsearch/reference/current/object.html)
List，默认：[object](https://www.elastic.co/guide/en/elasticsearch/reference/current/object.html)
map、dictionary，默认：[flattened](https://www.elastic.co/guide/en/elasticsearch/reference/current/flattened.html)

es的类型，参数官方文档：https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-types.html

**Comment by gelin9527** [comment]
已修复
